2025-11-22

diff --git a/.github/workflows/blog-analysis.yml b/.github/workflows/blog-analysis.yml
--- a/.github/workflows/blog-analysis.yml
+++ b/.github/workflows/blog-analysis.yml
@@ -24,16 +24,6 @@ jobs:
     - name: Build site
       run: npm run docs:build
 
-    - name: Generate Bundle Stats
-      run: |
-        npx bundle-stats --out-dir ./analysis --html --json
-
-    - name: Upload Bundle Report
-      uses: actions/upload-artifact@v4
-      with:
-        name: bundle-report
-        path: analysis
-
     - name: Run Lighthouse
       uses: treosh/lighthouse-ci-action@v11
       with:
@@ -46,7 +36,12 @@ jobs:
       id: prepare
       run: |
         mv .lighthouseci/*.html ./lighthouse-report.html
-        mv analysis/index.html ./bundle-stats.html
+        if [ -f stats.html ]; then
+            mv stats.html ./bundle-stats.html
+        else
+            echo "Error: stats.html not found!"
+            exit 1
+        fi
         
         cp .github/analysis-template.html email.html
 
@@ -56,8 +51,17 @@ jobs:
         sed -i "s|{{DATE}}|$CURRENT_TIME|g" email.html
         sed -i "s|{{YEAR}}|$CURRENT_YEAR|g" email.html
         sed -i "s|{{REPO}}|${{ github.repository }}|g" email.html
+    - name: Upload Analysis Reports
+      uses: actions/upload-artifact@v4
+      with:
+        name: Blog-Analysis-Report  # 在 GitHub 页面上显示的压缩包名字
+        path: |
+            lighthouse-report.html
+            bundle-stats.html
+        retention-days: 365
 
-    - name: Send email
+
+    - name: Send email  
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: smtp.qq.com
